name = "julia_test_repo"
uuid = "acd6f84b-e7ea-4772-a836-17337ee18937"
authors = ["lukasz.radzinski <lukasz.radzinski@aidlab.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
